sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t marcelbritto/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marcelbritto/docker-react npm run test
